Cypress.Commands.add('Register',()=>{
    cy.visit('https://www.automationexercise.com/login')
    cy.get('img').should('be.visible')
    cy.get('[data-qa="signup-name"]').type('Michael')
    cy.get('[data-qa="signup-email"]').type('michaeltemi2023+6@gmail.com')
    cy.get('[data-qa="signup-button"]').click()
    cy.get('#id_gender1').click({force:true})
    cy.get('[data-qa="password"]').type('Ultimate@90')
    cy.get('[data-qa="first_name"]').type('Michael')
    cy.get('[data-qa="last_name"]').type('Akintayo')
    cy.get('[data-qa="company"]').type('TREDOM')
    cy.get('[data-qa="address"]').type('Victoria Island')
    cy.get('[data-qa="address2"]').type('Lagos Island')
    cy.get('[data-qa="state"]').type('Lagos')
    cy.get('[data-qa="city"]').type('Lagos')
    cy.get('[data-qa="zipcode"]').type('100001')
    cy.get('[data-qa="mobile_number"]').type('08132453280')
    cy.get('[data-qa="country"]').select("United States")
    cy.get('[data-qa="days"]').select("25")
    cy.get('[data-qa="months"]').select("5")
    cy.get('[data-qa="years"]').select("2010")
    cy.get('[data-qa="create-account"]').click()
    
})

Cypress.Commands.add('Login',()=>{
    cy.visit('https://www.automationexercise.com/login')
    cy.get('img').should('be.visible')
    cy.get('[data-qa="login-email"]').type('michaeltemi2023@gmail.com')
    cy.get('[data-qa="login-password"]').type('Ultimate@90')
    cy.get('[data-qa="login-button"]').click()
   
})

Cypress.Commands.add('ProductsToCart',()=>{
    cy.visit('https://www.automationexercise.com/login')
    cy.get('img').should('be.visible')
    cy.get('[data-qa="login-email"]').type('michaeltemi2023@gmail.com')
    cy.get('[data-qa="login-password"]').type('Ultimate@90')
    cy.get('[data-qa="login-button"]').click()
    cy.get(':nth-child(4) > .product-image-wrapper > .single-products > .productinfo > .btn').click()
    cy.get('.modal-footer > .btn').click()
    cy.get(':nth-child(9) > .product-image-wrapper > .single-products > .productinfo > .btn').click()
    cy.get('.modal-footer > .btn').click()
    cy.get(':nth-child(12) > .product-image-wrapper > .single-products > .productinfo > .btn').click()
    cy.get('.modal-footer > .btn').click()
    cy.get(':nth-child(16) > .product-image-wrapper > .single-products > .productinfo > .btn').click()
    cy.get('.modal-footer > .btn').click()
    cy.get(':nth-child(23) > .product-image-wrapper > .single-products > .productinfo > .btn').click()
    cy.get('.modal-footer > .btn').click()
    cy.get('.shop-menu > .nav > :nth-child(3) > a').click()
    // cy.get('#cart_items > :nth-child(1)').should('be.greaterThan', 3)
    cy.get('.col-sm-6 > .btn').click()
    cy.contains('Checkout')
    cy.get(':nth-child(7) > .btn').click()
    cy.contains('Payment')
    cy.get('[data-qa="name-on-card"]').type('Michael Akintayo')
    cy.get('[data-qa="card-number"]').type('506156748973456789')
    cy.get('[data-qa="cvc"]').type('959')
    cy.get('[data-qa="expiry-month"]').type('03')
    cy.get('[data-qa="expiry-year"]').type('2025')
    cy.get('[data-qa="pay-button"]').click()
    cy.get('[data-qa="order-placed"] > b').should('be.visible')
    cy.get('.col-sm-9 > .btn-default').click()
    cy.get('.nav > :nth-child(4) > a').click()
   
})